version: 2
jobs:
  build:
    working_directory: /home/projects/github.com/kyoh86/xdg
    docker:
      - image: kyoh86/gotest:latest
    steps:
      - checkout
      - run:
          name: install
          command: go install ./...
      - run:
          name: test and take coverage
          command: |
            mkdir -p .circleci/test/gotest
            go test -v -race -coverprofile=coverage.out ./... | go-junit-report > .circleci/test/gotest/results.xml;
      - run:
          name: upload coverage
          command: bash <(curl -s https://codecov.io/bash)
      - run:
          name: search lints
          command: golangci-lint run


workflows:
  version: 2
  commit:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
