name: Test

on:
  push:
    branches: '*'

jobs:
  test:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - uses: actions/checkout@v2
      - name: get dependencies
        run: go get -v -t -d ./...

      - name: test race
        run: go test -v -race ./...

  lint-and-cover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - uses: actions/checkout@v2
      - name: get dependencies
        run: go get -v -t -d ./...
      - name: vendoring
        run: go mod vendor

      # - uses: kyoh86/action-golangci-lint@v1 

      - name: take coverage
        run: go test -coverprofile=coverage.txt -covermode=count ./...
      - uses: codecov/codecov-action@v1.0.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.txt

