name: Test

on:
  push:
    branches: '*'

jobs:
  test:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: get dependencies
        run: go get -v -t -d ./...

      - name: test race
        run: go test -v -race ./...

  lint-and-cover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: get dependencies
        run: go get -v -t -d ./...
      - name: vendoring
        run: go mod vendor

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.32

      - name: take coverage
        run: go test -coverprofile=coverage.txt -covermode=count ./...
      - uses: codecov/codecov-action@v1.0.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.txt

